### ISSUE TITLE
Implementation of Field-aware Factorisation Machines

### ISSUE THREAD

**Issue by ivanpartsianka** [myui/hivemall#273]
Does it make sense to implement http://ntucsu.csie.ntu.edu.tw/~cjlin/libffm/ (that showed good performance for the CTR prediction Kaggle competitions) on top of hive?

**Comment by myui** [comment]
Make sense to support Field-aware FM.

However, parallel processing of FM solely using Hive is hard because data parallel processing of FM requires additional parameter mixing scheme inside UDFs.
http://www.cs.cmu.edu/~yuxiangw/docs/fm.pdf
http://stanford.edu/~rezab/papers/factorbird.pdf

The current FM implementation should also support parameter mixing. Intending to implement it in v0.5.

**Comment by myui** [comment]
FFM Implementation is on-going w/ an intern student. Stay tuned.

**Comment by myui** [comment]
@ivanpartsianka Implemented. It will appear in the next release.
https://github.com/myui/hivemall/pull/284

**Comment by ivanpartsianka** [comment]
@myui thank you so much, guys. Really keen to try on real data
